/* (C) Disembodied and Svengali 2009-2018, License CC-by-nc-sa-4.0 */
(function(){
"use strict";
this.name = "GNN_Words";

this.pool = {
	GNN_Blessing:{
		fieldA: ["(X GNN_wish2)"],
		fieldB: ["(X GNN_bless1)"],
		fieldC: ["(X GNN_bless2)"],
		fieldD: ["(X GNN_bless3)"],
		fieldE: ["(X GNN_wish3)"],
		fieldF: ["(X GNN_P009)"],
		fieldG: [],
		fieldH: [],
		fieldI: [],
		fieldJ: [],
		fieldK: [],
		fieldL: [],
		fieldM: [],
		fieldN: [],
		fieldO: [],
		fieldP: [],
		fieldQ: [],
		fieldR: [],
		sentences: ["+1 [GNN_NamesGods] 2 you!","[GNN_NamesGods] 2 you!","+1 [GNN_NamesGods] 3 5 6!","+1 [GNN_NamesGods] 4 you with 5!"]
	},
	GNN_CommWelcome:{
		fieldA: ["(Y0x30=[2], [7]|[3])"],
		fieldB: ["(X GNN_status1)"],
		fieldC: ["(Y0x6=[4].|[5], [6])"],
		fieldD: ["(X GNN_welcome1)","(X GNN_welcome2)"],
		fieldE: ["Glad to see you, Sir","It's good that you're here, Commander","(X GNN_welcome1)"],
		fieldF: ["(Y0x200021=[7]|[8])"],
		fieldG: ["(X GNN_join1)"],
		fieldH: ["(X GNN_status2)"],
		fieldI: ["over."],
		fieldJ: ["(B7=[2]|[3])"],
		fieldK: ["Who do you think you are... [9]?","You vicious [8]!","(X GNN_threat2)"],
		fieldL: ["(Y0x4100=[4]|[5])"],
		fieldM: ["You stupid [8]!","(X GNN_threat3)"],
		fieldN: ["(B6=[6],|[7])"],
		fieldO: ["Bah","Nah","Jeeze","(X GNN_inter1)"],
		fieldP: ["(X GNN_ask1)","(X GNN_askleave1)"],
		fieldQ: ["(X GNN_bandit1)"],
		fieldR: ["(X GNN_bandit2)"],
		sentences: ["(Y0x50c0={)+1 @Y1, }9","@Y1 here. (Y0x50c0={)+1","(Y0x50c0={)+(B7=[GNN_PirateInsult]|[1]) @Y1, }9"],
		custom: [0xc0002,"Captain Illych Bartok"],
		splitRules: []
	},
	GNN_Names:{
		fieldA: ["Aga[8]","Aid[4]","Ala[5]","Al[6]","An[4]","Ar[7]","Ay[4]","Balde[3]","Bal[4]","Bar[5]","Beo[3]","Boro[5]","Bran[3]","Bray[6]","Bra[9]","Bren[9]","Cal[3]","Ced[4]","Clem[9]","Col[3]","Cor[3]","Co[9]","Dago[5]","Dan[7]","Den[9]","Dor[7]","Dor[8]","Drago[5]","Dun[7]","Ed[6]","El[4]","Eme[2]","Eo[7]","Fin[7]","Gala[3]","Gal[4]","Gar[2]","God[9]","Gor[3]","Har[7]","Jeg[3]","Jew[6]","Ker[3]","Mal[3]","Mar[3]","Nor[6]","Palo[5]","Peli[3]","Ran[4]","Rey[6]","Re[4]","Re[7]","Ri[4]","Ro[5]","Ter[2]","Wal[4]","Wes[7]","Wil[6]","Y[3]","(X GNN_names1)","(X GNN_names4)"],
		fieldB: ["reth","rett","sch"],
		fieldC: ["(X GNN_syl2)"],
		fieldD: ["ders","drew","drick","dy","ek","mund","ric"],
		fieldE: ["bar","man","mir"],
		fieldF: ["bert","dy","gar","mon","mond"],
		fieldG: ["gar","ley","mer","n","nall","ward"],
		fieldH: ["karr","khan","mir","rath","son"],
		fieldI: ["dall","dan","ders","drick"],
		fieldJ: ["(X GNN_syl3)"],
		fieldK: ["(X GNN_syl4)"],
		fieldL: ["(X GNN_syl5)"],
		fieldM: ["(X GNN_names13)"],
		fieldN: ["(X GNN_names14)"],
		fieldO: ["(X GNN_names15)"],
		fieldP: [],
		fieldQ: [],
		fieldR: [],
		sentences: ["1 {12","1 {13","1 +{46","1 +{56","1 +{52","1 [GNN_NamesOolite]"],
		splitRules: [1,1,1,1,1,1]
	},
	GNN_NamesBrews:{
		fieldA: ["(X GNN_brew1)"],
		fieldB: ["(X GNN_brew2)"],
		fieldC: ["(X GNN_brew3)"],
		fieldD: ["(X GNN_brew4)"],
		fieldE: ["(X GNN_brew5)"],
		fieldF: [],
		fieldG: [],
		fieldH: [],
		fieldI: [],
		fieldJ: [],
		fieldK: [],
		fieldL: [],
		fieldM: [],
		fieldN: [],
		fieldO: [],
		fieldP: [],
		fieldQ: [],
		fieldR: [],
		sentences: ["@s's 1 3 4","3 4","3's 5","1 3","2 3 4","2 3's 5","2 1 3"],
		splitRules: [22,22,22,22,22,22,22]
	},
	GNN_NamesGods:{
		fieldA: ["(X GNN_god4)"],
		fieldB: ["(X GNN_god5)"],
		fieldC: ["many","(X GNN_few2)","(X GNN_few3)"],
		fieldD: ["eyes","heads","hands","horns","limbs","tongues","eggs","hosts"],
		fieldE: ["eyed","headed","handed","horned"],
		fieldF: [],
		fieldG: [],
		fieldH: [],
		fieldI: [],
		fieldJ: ["(X GNN_sh1)","(X GNN_syl6)"],
		fieldK: ["(X GNN_sh2)","(X GNN_syl7)"],
		fieldL: ["(X GNN_sh1)","(X GNN_syl8)"],
		fieldM: ["(X GNN_sh2)","(X GNN_syl9)"],
		fieldN: ["(X GNN_names3)"],
		fieldO: [],
		fieldP: [],
		fieldQ: [],
		fieldR: [],
		sentences: ["+1 {12","{12 the }+2","{12 of the }+3 +4","+3-5 {12","+1 {12 of the }+3 +4","+1 {34","{34 the }+2","{34 of the }+3 +4","+3-5 {34","+1 {34 of the }+3 +4","+1 {5","{5 the }+2","{5 of the }+3 +4","+3-5 {5","+1 {5 of the }+3 +4"]
	},
	GNN_NamesOolite:{
		fieldA: [],
		fieldB: ["[2]-[3]","ben [3]","Mc[3]","Ol'[3]","Ath[5]","Br[9]an","Bran[4]","C[7][4]","D[7][4]","Dav[9][4]","Denn[9][4]","Eccl[5]","Fa[9]r[4]","Folk[4]","Garr[5]","Good[4]","Hector","Inn[5]","Jam[5]","Jon[4]","Kir[4]","L[9]ttle[4]","L[7][4]","Na[9]l[4]","Neil[4]","Peter[4]","Orbit[4]","Roger[4]","Sam[4]","Star[4]","Th[8]r[4]","Wilkin[4]","William[4]"],
		fieldC: ["Ath[5]","Br[9]an","Bran[4]","C[7][4]","D[7][4]","Dav[9][4]","Denn[9][4]","Folk[4]","Garri[4]","Good[4]","Hector","Inn[5]","Jam[5]","Jon[4]","Kir[4]","L[9]ttle[4]","L[7][4]","Na[9]l[4]","Neil[4]","Peter[4]","Roger[4]","Sam[4]","Star[4]","Th[8]r[4]","Wilkin[4]","William[4]"],
		fieldD: ["b[8]rn","f[8]r","st[8]n","sen","son","son","sdott[9]r","s","s","sby","er","f[9]re","l[9]ng"],
		fieldE: ["e","[6]b[8]rn","[6]f[8]r","[6]st[8]n","[6]sen","[6]son","eson","[6]sdott[9]r","[6]s","es","esby","[6]f[9]re","l[9]ng"],
		fieldF: ["i","e","e","ie"],
		fieldG: ["ar","aw","arre","our"],
		fieldH: ["e","o","u","ou","ai"],
		fieldI: ["i","y"],
		fieldJ: [],
		fieldK: [],
		fieldL: [],
		fieldM: [],
		fieldN: [],
		fieldO: [],
		fieldP: [],
		fieldQ: [],
		fieldR: [],
		sentences: ["3","2"],
		splitRules: [2,2]
	},
	GNN_NamesOther:{
		fieldA: ["(X GNN_sh1)","(X GNN_syl6)"],
		fieldB: ["(X GNN_syl1)"],
		fieldC: ["(X GNN_syl7)"],
		fieldD: ["(X GNN_names3)"],
		fieldE: [],
		fieldF: [],
		fieldG: ["(B28+)(B29+)[2][3]"],
		fieldH: ["[4]"],
		fieldI: ["[1][2]","[2][3]"],
		fieldJ: ["(B28+)(B29+)[2]"],
		fieldK: ["Al","Alex","Alto","Amanda","Amber","Apollo","Baldrin","Beck[3]","Begg[3]","Biff","Bonnie","Brooke","Buck[3]","Cain","Check[3]","Chip","Churchill","Claire","Clifford","Constantine","Dakota","Darren","Dick[3]","Don","Dugg[3]","Dusty","Ernie","Fanny","Felix","Ford","Frenzy","Ginger","Hannibal","Holly","Jack","Joaquin","Kipper","Mack[3]","Marlon","Mick[3]","Mo","Montgomery","Moritz","Myles","Nat","Orion","Penny","Reav[3]","Red","Rock[3]","Ryan","Sal","Sand[3]","Tiff[3]"],
		fieldL: ["annie","ers","ie","y"],
		fieldM: [],
		fieldN: ["(B28+)(B29+)[6]"],
		fieldO: ["(X GNN_names12)"],
		fieldP: [],
		fieldQ: ["(B28+)(B29+)[9]"],
		fieldR: ["(X GNN_names16)"],
		sentences: ["{+(Si:rodent=[1]|)+(Si:feline=[1]|)+(Si:bird=[5]|)+(Si:frog=[8]|)}+(Si:lobster=[7]|)+(Si:lizard=[8]|)+(Si:insect=[9]|)+{(Si:human=[8]|) {+(B28=|[9])+(B29=[GNN_NamesOolite]|)"],
		splitRules: [1]
	},
	GNN_NamesPirates:{
		fieldA: ["(X GNN_names6)","[6]shanks"],
		fieldB: ["(X GNN_names1)","(X GNN_names2)"],
		fieldC: [],
		fieldD: ["(X GNN_names7)","[8]balls","[8]beard","Mc[2]"],
		fieldE: ["(X GNN_names11)","The Rusty [7]"],
		fieldF: ["(X GNN_color2)"],
		fieldG: ["Butter Cutter","Broadsword","Cutlass","Dagger","Epee","Knife","Saber","Scabbard"],
		fieldH: ["(X GNN_color1)"],
		fieldI: [],
		fieldJ: [],
		fieldK: [],
		fieldL: [],
		fieldM: [],
		fieldN: [],
		fieldO: [],
		fieldP: [],
		fieldQ: [],
		fieldR: [],
		sentences: ["2 '1' 4","2 '5' 4","2 '5' 4","2 '1' 4","Long 2 4"],
		splitRules: [3,3,3,3,4]
	},
	GNN_NamesShips:{
		fieldA: ["(X GNN_names8)","(X GNN_color1)"],
		fieldB: ["(X GNN_names5)"],
		fieldC: ["(X GNN_names9)"],
		fieldD: ["(X GNN_title2)"],
		fieldE: ["(X GNN_names10)"],
		fieldF: [],
		fieldG: [],
		fieldH: [],
		fieldI: [],
		fieldJ: [],
		fieldK: [],
		fieldL: [],
		fieldM: [],
		fieldN: [],
		fieldO: [],
		fieldP: [],
		fieldQ: [],
		fieldR: [],
		sentences: ["The 1 2","The 1 3","The +4 2","The +4 5"],
		splitRules: [21,21,21,21]
	},
	GNN_PirateInsult:{
		fieldA: ["(X GNN_anim1)"],
		fieldB: ["(X GNN_body1)"],
		fieldC: ["(X GNN_bucket1)"],
		fieldD: ["(X GNN_spit1)"],
		fieldE: ["(X GNN_god3)"],
		fieldF: ["(X GNN_god2)"],
		fieldG: ["(X GNN_god1)"],
		fieldH: ["(X GNN_insult1)"],
		fieldI: ["(X GNN_wish1)"],
		fieldJ: ["(X GNN_threat1)"],
		fieldK: [],
		fieldL: [],
		fieldM: [],
		fieldN: [],
		fieldO: [],
		fieldP: [],
		fieldQ: [],
		fieldR: [],
		sentences: ["9 5 |7 8 your 2!","9 5 |7 8 your 2, you 1!","9 5 |7 8 your 2, you 6 1!","9 5 |7 8 your 2, you 6 3 of 4!","9 5 |7 8 your 2, you 6 3 of 1 4!","9 5 |7 of @s 8 your 2!","9 5 |7 of @s 8 your 2, you 1!","9 5 |7 of @s 8 your 2, you 6 1!","9 5 |7 of @s 8 your 2, you 6 3 of 4!","9 5 |7 of @s 8 your 2, you 6 3 of 1 4!","You 1!","You 6 1!","You 6 3 of 4!","You 6 3 of 1 4!","{1 }8 you!","{1 }8 you, you 1!","{1 }8 you, you 6 1!","{1 }8 you, you 6 3 of 4!","{1 }8 you, you 6 3 of 1 4!","{1 }8 your 2!","{1 }8 your 2, you 1!","{1 }8 your 2, you 6 1!","{1 }8 your 2, you 6 3 of 4!","{1 }8 your 2, you 6 3 of 1 4!"]
	},
	GNN_Precious:{
		fieldA: ["(X GNN_color1)","(X GNN_color2)","(X GNN_color3)","(X GNN_god3)"],
		fieldB: ["(X GNN_anim1)","(X GNN_god1)","(X GNN_precious1)"],
		fieldC: ["(X GNN_bucket1)"],
		fieldD: ["(X GNN_bottle1)"],
		fieldE: [],
		fieldF: [],
		fieldG: [],
		fieldH: [],
		fieldI: [],
		fieldJ: [],
		fieldK: [],
		fieldL: [],
		fieldM: [],
		fieldN: [],
		fieldO: [],
		fieldP: [],
		fieldQ: [],
		fieldR: [],
		sentences: ["1 +>2","3 of 1 +>2","4 of [GNN_NamesBrews]","1 +>2","3 of 1 +>2"]
	},
	GNN_A:{
		fieldA: ["(X GNN_factory1)","(X GNN_govhouse1)","(X GNN_house1)","(X GNN_install1)"],
		fieldB: ["(X GNN_incident1)"],
		fieldC: ["(X GNN_big1)"],
		fieldD: ["(X GNN_many1)"],
		fieldE: ["county seat","(X GNN_major1)"],
		fieldF: ["(X GNN_inofficial1)"],
		fieldG: ["(X GNN_document1)"],
		fieldH: ["(X GNN_destroy1)"],
		fieldI: ["(X GNN_reveal1)"],
		fieldJ: ["(X GNN_device1)"],
		fieldK: ["(X GNN_tragedy1)"],
		fieldL: ["(X GNN_inoperable1)"],
		fieldM: ["(X GNN_official1)"],
		fieldN: ["(X GNN_P006)"],
		fieldO: ["(X GNN_P007)"],
		fieldP: ["(X GNN_P008)"],
		fieldQ: ["(X GNN_inoperable2)"],
		fieldR: ["in the next days","within the next days"],
		sentences: ["@XA 3 2 _8 4 >1 at >@s 5 district, injuring 4 (X GNN_citizen1) earlier this morning. 6 >7 9 that this {2 could have been ^3, but ^8 >1 ^3 the >7. '6,' said (Si:human=[GNN_Names]|[GNN_NamesOther]), >@s 4. 'But the }3 {2 }_8 important structures here{5 9.'"]
	},
	GNN_B:{
		fieldA: ["(X GNN_citizen1)","(X GNN_trader1)"],
		fieldB: ["expressed approval of","applauded","celebrated","cheered","hailed","acclaimed"],
		fieldC: ["notorious","infamous","feared"],
		fieldD: ["(X GNN_bandit1)"],
		fieldE: ["plagued","afflicted","cursed","preyed on","attacked"],
		fieldF: ["in recent","for many","for the last several"],
		fieldG: ["weeks","months","years"],
		fieldH: ["Adjudicator","Judge","(Sg:0=local chieftain|[9])","(Sg:1=Sheriff|[9])","(Sg:1=Royal Justiciar|[9])","(Sg:1=King's Hand|[9])","(Sg:3=State Prosecutor|[9])","(Sg:3=Archimandrite|[9])","(Sg!4=Priest of Justice|[9])","(Sg:4=People's Representative|[9])","(Sg:4=State Prosecutor|[9])","(Sg:4=People's Justice|[9])","(Sg:5=Protector of the Commonwealth|[9])","(Sg:6=Arbiter|[9])","(Sg:6=Counsellor|[9])","(Sg:7=Director|[9])","(Sg:7=Personnel Manager|[9])","(Sg:7=Supervisor|[9])"],
		fieldI: ["Adjudicator","Judge","Arbiter"],
		fieldJ: ["(Sg<5=[2]|deprogramming)","(Sg<5=[2]|brainwashing)","(Sg<5=[2]|brain wipe)","(Sg<5=[2]|re-education)","(Sg<5=[2]|community service)","(Sg<3=vitrification|[2])","(Sg:7=reduction in salary|[2])"],
		fieldK: ["(Se<7=death|throat-cutting)","slow death","(Sg<1=drawing and quartering|immurement)","penal servitude","death of personality","brain wipe"],
		fieldL: ["Addressing the court","On being dragged from the courtroom","With bulging eyes","With a certain dignity","Struggling with the guards","Visibly appalled","Clearly terrified","Shaking with fear"],
		fieldM: ["prisoner","felon","miscreant","guilty party"],
		fieldN: ["murmured","yelled","screamed","shouted","said","shrieked"],
		fieldO: ["amuse","enrage","anger","tickle","entertain","bewilder","confuse","puzzle"],
		fieldP: ["lively","eager","exuberant","festive","excited","feverish","frantic"],
		fieldQ: ["crowd","rabble","throng","mob","(Sg:1=courtiers|[9])","(Sg:4=Party members|[9])","(Sg>4=media|[9])","(Sg:7=executives|[9])"],
		fieldR: ["crowd","rabble","throng","mob"],
		sentences: ["@s, @d.@c: Local >1 2 the capture of [GNN_NamesPirates], the 3 4 who has 5 shipping in this and nearby systems 6 7. The 8, @W, sentenced @n0 to {1. 3 the 4 5, '[GNN_PirateInsult]', which only served to 6 the 7 8.","@s, @d.@c: A {7 9 of >}1 looked on as [GNN_NamesPirates] was today found guilty on all counts. Summing up, 8 @W called the prisoner 'a 3 4, who has 5 local shipping 6 7'. {3, @n0 5, '[GNN_PirateInsult]', which seemed to 6 @n1. Traders' Guild representatives }2 @n1 as @n0 was sentenced to {1."]
	},
	GNN_C:{
		fieldA: ["(X GNN_serious1)"],
		fieldB: ["(Sg:0=tribespeople|[2])","(Sg:0=warriors|[2])","(Sg:1=nobles|[2])","(Sg:1=peasants|[2])","(Sg:3=fanatics|[2])","(Sg:4=Party members|[2])","(Sg:7=executives|[2])","(Si:human=colonists|[2])","media","inhabitants","citizens"],
		fieldC: ["offended","transgressed","broke","violated","flouted","outraged"],
		fieldD: ["(Sg!4=religious precepts|[4])","laws","customs","mores","morality","traditions","norms","codes of behaviour","conventions"],
		fieldE: ["touching","looking at","speaking to","smiling at","winking at","kicking","shouting at","eating","whistling at","singing to","whistling near","tickling","abusing","insulting","(Sg!4=denying the sanctity of|[5])","(Sg:4=oppressing|[5])","coughing near","sneezing within earshot of","laughing at","soiling","ogling"],
		fieldF: ["frozen","pickled","(Sg:1=Royal|[6])","(Sg!4=sacred|[6])","(Sg!4=holy|[6])","unwashed","veiled","blue","white","green","purple","cross-eyed","one-eyed","three-eyed","drunken","sleeping","preserved","painted","(Sg<4=low-caste|[6])","(Sg<4=high-caste|[6])"],
		fieldG: ["(Sg!4=priest|[7])","(Sg!4=priestess|[7])","(Sg!4=idol|[7])","(Sg!4=divinity|[7])","(Sg!4=fetish|[7])","goat","monkey","shrew","chicken","poet","treeoid","bat","Elder","ant","opossum","sheep","bison","buffalo","pig","ferret","weasel","gibbon","baboon","porcupine","pachyderm","(Sg:2=courtier|[7])","(Sg:4=senior Party member|[7])","(Sg:7=member of the Board|[7])"],
		fieldH: ["(X GNN_rumour1)"],
		fieldI: ["twelve","twenty-four","(X GNN_few2)"],
		fieldJ: ["hours","days"],
		fieldK: ["(X GNN_mob1)"],
		fieldL: ["an apology","the ambassador's resignation","the ambassador's head","compensation for mental anguish","'an end to Co-operative brutality'","the withdrawal of Co-operative forces from the system","atonement","nothing less than the breakup of the Co-operative","the ambassador's surrender","justice"],
		fieldM: ["political reputations","delicate trade negotiations","diplomatic careers","planetary honour and pride","the fates of worlds"],
		fieldN: ["(X GNN_ending1)"],
		fieldO: ["scandal has erupted following the arrival of"],
		fieldP: ["the new Co-operative ambassador to"],
		fieldQ: ["Although the ambassador's staff have denied the allegations, calling them"],
		fieldR: ["the Co-operative embassy has been surrounded by"],
		sentences: ["A 1 {6 (Si:human=[GNN_Names]|[GNN_NamesOther])}, a @h from @s, as {7} @S. Local 2 claim that @n 3 @s 4 by 5 a 6 7. @n's staff deny the allegations, calling them '8'. Nevertheless, for the last 9 {1, 9 2 of protestors demanding 3. 4 hang in the balance5","(Si:human=[GNN_Names]|[GNN_NamesOther]), a @h from @s and {7} @S, is today at the centre of a 1 scandal. {2 of local }2 have surrounded the embassy, claiming that @n 3 @s 4 by 5 a 6 7. {8} '8', angry voices are demanding {3. 4 are at stake here5"],
		custom: [0x0],
		splitRules: []
	},
	GNN_D:{
		fieldA: ["(X GNN_react1)"],
		fieldB: ["(X GNN_claims1)"],
		fieldC: ["(X GNN_fail1)"],
		fieldD: ["(X GNN_P005)"],
		fieldE: ["a number of","several","three","four","five","six","seven","eight","nine","ten","eleven","twelve","more than a dozen","more than fifteen","more than twenty","an estimated twenty-two","more than two dozen","dozens of","a great many"],
		fieldF: ["(X GNN_ships2)"],
		fieldG: ["ranking GalCop officer","GalCop commander","Viper squadron leader","GalCop co-ordinator"],
		fieldH: ["we are doing the best we can within a very limited budget","we put our lives on the line every day","we do not shirk our duty","we simply do not have sufficient forces available","our own losses were considerable","our pilots are severely overstretched","we cannot work miracles","this attack was unprecedented in scale","we are not to blame here"],
		fieldI: ["levelled accusations that","claimed that","presented evidence which purported to show that","displayed evidence that","suggested that"],
		fieldJ: ["(Sg:1=crown officers|[1])","(Sg:1=nobles|[1])","(Sg:3=state police|[1])","(Sg:3=security|[1])","(Sg:4=Party members|[1])","(Sg:7=executives|[1])","(Sg:7=salarymen|[1])","(Sg:7=accountants|[1])","officials","administrators","agents"],
		fieldK: ["delayed","misused","misappropriated","stolen","failed to provide","siphoned off","purloined","embezzled"],
		fieldL: ["funds","moneys","resources","supplies","assets","stores","reserves","finances"],
		fieldM: ["required by","intended for","needed by","urgently needed by","desperately needed for","which rightfully belonged to"],
		fieldN: ["system patrols","Viper patrols","system police","GalCop forces","Co-operative forces","local Viper pilots"],
		fieldO: ["at this time","at this moment","right now","For the moment","currently","at this point","just now","presently,","as things stand","given the circumstances","with so many of our members lost,"],
		fieldP: ["who is to blame","who is at fault","who is responsible","who is culpable","where the fault lies","what the problem is"],
		fieldQ: ["want a fighting chance","need all parties to work together","want to prevent this tragedy from repeating itself","need everyone to do their job"],
		fieldR: ["are still unaccounted for","cannot be accounted for","are listed as 'overdue'","are missing, presumed destroyed","cannot be located","have disappeared from the system","are missing: hopefully both jumped out safely"],
		sentences: ["@s, @d.@c: GalCop _1 2 that they 3 a 4, (X GNN_P001) 5 >6 (X GNN_P002). [GNN_Names], the 7, said, '+8,' and 9 @s {1 had 2 3 4 5. (X GNN_P003) [GNN_Names] said, '+6 we don't care 7: we just 8.' (X GNN_P004) the }6 '[GNN_NamesShips]' and '[GNN_NamesShips]' {9.","@s, @d.@c: [GNN_Names], the local 7, has 9 @s {1 have 2 3 4 5. Planetary representatives }_1 @n's statement, issuing their own 2 that {5 }3 a recent 4, which resulted in the destruction of 5 >6 across the system. Merchants' Guild representative [GNN_Names] said, '{+6 we don't care 7: we just 8.' Since the attack, the }6 '[GNN_NamesShips]' and '[GNN_NamesShips]' {9."]
	},
	GNN_TraderCharacter:{
		fieldA: ["affected(B3+)","annoying","big","bohemian(B1+)","burly","cantankerous","chaotic(B0+)","childlike","cold","cosmopolitan(B1+)","dirt-encrusted","discreet","eloquent","famous","fashionable","fearless","flabby","fractured","funny","furious","gentle","greasy(B0+)","greedy","grim(B1+)","grinning(B1+)","grumpy","honourable(B1+)","lively","magnificent(B1+)","mean-spirited","memorable","miserly","misty(B0+)","mitochondrial","modest","moronic","most difficult","mysterious","nearly blind(B0+)","old","one-eyed(B0+)","paternal","pathetic","pompous(B1+)","psychotic(B1+)","raspy(B0+)","ravishing","reactionary(B0+)","respectable(B1+)","resplendent","righteous","rough","rude(B1+)","rum","salty(B0+)","shabby","slow","small","smelly(B0+)","statesmanlike(B1+)","stoic","stormy","tattered(B0+)","well-known(B1+)","worldly(B1+)"],
		fieldB: [" and (B0=[5]|[4]) of [6]"],
		fieldC: ["(D50=Junior Chief|[5])","Chief Scientist(B3+)","Director(B3+)","Executive Chief(B3+)","Senior Chief(B3+)","Senior Coordinator(B3+)"],
		fieldD: ["(B1=[3]|Design Specialist)","(B1=[3]|Sales Manager)","(D50=Junior Chief|[5])","Operating [5]","Trade (D50=[5]|Coordinator)"],
		fieldE: ["Assistant(B2+)","Attendant(B2+)","Engineer(B2+)","Manager(B2+)"],
		fieldF: ["[8]","Amber [7]","AMS [7]","B.AT Inc","Betaex [7]","Borland [7]","Citek [7]","Citex [7]","Citgoo Express","Clifford [7]","Conestrip [7]","Connex [7]","Dalmore [7]","Daltlane [7]","deVane [7]","Dingi [7]","ETS [7]","Faulcon [7]","FreshFoods Inc","Fujio [7]","FullGrip [7]","Grupo Langostaides Azules","Huginkiss [7]","Hydrotec [7]","Inditech [7]","InterDrew [7]","Joover [7]","KMC [7]","Lave Fried Trumble Inc","Leysson [7]","Lifetec [7]","Ligoos [7]","Lucky Vole Farms","Mana [7]","Milford [7]","Monu Pharma","Nano [7]","NoVidio [7]","OO-Haul [7]","Oops Deliveries","PIn-tel Limited","PlaneOptics [7]","Plummer [7]","Ret Vesla Clothings","Saltlane [7]","Silvercon [7]","Siretex [7]","Stimtatex [7]","Subtech [7]","Takahara [7]","Texacoo Fuel [7]","the KitiTec Ltd","the Onix Inc","the Oomoo [7]","the Weyland-Yutani Corporation","Warfeld [7]","Wencoo [7]","Xenophob [7]","ZA Brew Ltd"],
		fieldG: ["(X GNN_company2)"],
		fieldH: ["Balder [9]","Emerson [9]","Palmer [9]","Greening [9]","Parker [9]","Nomuhare [9]"],
		fieldI: ["and Sons Ltd","Inc","and Balder [7]","and Emerson [7]","and Palmer [7]","and Greening [7]","and Parker [7]","and Partners"],
		fieldJ: ["co-owner of","commandeering","Commander of","holder of","operating","owner of","patron of","piloting","skipper of","taskmaster of"],
		fieldK: ["compact (D50=[3]|[4])","escorted (D50=[3]|[4])","(B2=fast [4]|heavy [3])","finely crafted [3]","guarded [3]","(B2=un|heavily )escorted (D50=[3]|[4])","light escorted (D50=[3]|[4])","light guarded (D50=[3]|[4])","light (B1=[4]|[5])","(B3=experimental|maneuverable) (D50=[4]|[5])","medium (D50=escorted [4]|guarded [3])","medium [4]","(B2=small [5]|slim [4])"],
		fieldL: ["(B3=Python|Anaconda) [6]","Python [6]","Boa [6]","Boa II [6]","Boa Class Cruiser","(B3=Ferdelance|Anaconda) [6]","Python [6]"],
		fieldM: ["Cobra Mk III [7]","Ferdelance [7]","Moray Medical Boat [7]","Moray Star Boat [7]","Cobra Mk III [7]"],
		fieldN: ["Adder(B2+) [7]","Asp(B2+) [7]","Cobra Mk I(B2+) [7]","Gecko(B2+) [8]","Krait(B2+) [8]","Mamba(B2+) [8]","Sidewinder(B2+) [8]","Cobra Mk I(B2+) [7]","Adder(B2+) [7]"],
		fieldO: ["(B3=liner|barge)","(B3=yacht|cargo ship)","(B3=cruiser|cargo shuttle)","craft","cruiser","(B3=yacht|ferry)","(B2=ore ship|cruiser)","scientific vessel","schooner","solar-sail","starship","(B3=cargo steamer|tradeship)","transport","vessel"],
		fieldP: ["(B3=yacht|cargo shuttle)","craft","(B3=merchant ship|ferry)","(B3=scientific|privateer) ship","skiff","sloop","scow","(B3=prototype|scout ship)","(B2=skiff|shuttle)"],
		fieldQ: ["craft","privateer ship","skiff","sloop","scow","scout ship"],
		fieldR: [],
		sentences: ["@XCaptain @W, a 1 @h from @s(D30=[2]|), {1 '[GNN_NamesShips]', a 2."]
	}
};
this.irregularNouns = {
	bison:"bison",
	carp:"carp",
	genie:"genii",
	gold:"gold",
	mouse:"mice",
	oni:"oni",
	ox:"oxen",
	seraph:"seraphim",
	shrimp:"shrimp",
	squid:"squid",
	trout:"trout"
};
this.irregularVerbs = {
	arise:["arise","arises","arose","arisen"],
	awake:["awake","awakes","awoke","awoken"],
	backslide:["backslide","backslides","backslid","backslid"],
	be:["be","is","was","been"],
	bear:["bear","bears","bore","born"],
	beat:["beat","beats","beat","beaten"],
	become:["become","becomes","became","become"],
	begin:["begin","begins","began","begun"],
	bend:["bend","bends","bent","bent"],
	bet:["bet","bets","bet","betted"],
	bid:["bid","bids","bid","bid"],
	bind:["bind","binds","bound","bound"],
	bite:["bite","bites","bit","bitten"],
	bleed:["bleed","bleeds","bled","bled"],
	blow:["blow","blows","blew","blown"],
	"break":["break","breaks","broke","broken"],
	breed:["breed","breeds","bred","bred"],
	bring:["bring","brings","brought","brought"],
	browbeat:["browbeat","browbeats","browbeat","browbeaten"],
	build:["build","builds","built","built"],
	burst:["burst","bursts","burst","burst"],
	buy:["buy","buys","bought","bought"],
	cast:["cast","casts","cast","cast"],
	"catch":["catch","catches","caught","caught"],
	choose:["choose","chooses","chose","chosen"],
	cling:["cling","clings","clung","clung"],
	come:["come","comes","came","come"],
	cost:["cost","costs","cost","cost"],
	creep:["creep","creeps","crept","crept"],
	crossbreed:["crossbreed","crossbreeds","crossbred","crossbred"],
	cut:["cut","cuts","cut","cut"],
	daydream:["daydream","daydreams","daydreamt","daydreamt"],
	deal:["deal","deals","dealt","dealt"],
	dig:["dig","digs","dug","dug"],
	dive:["dive","dives","dove","dived"],
	"do":["do","does","did","done"],
	draw:["draw","draws","drew","drawn"],
	dream:["dream","dreams","dreamt","dreamt"],
	drink:["drink","drinks","drank","drunk"],
	drive:["drive","drives","drove","driven"],
	eat:["eat","eats","ate","eaten"],
	fall:["fall","falls","fell","fallen"],
	"feast on":["feast on","feasts on","feasted upon","feasted upon"],
	feed:["feed","feeds","fed","fed"],
	feel:["feel","feels","felt","felt"],
	fight:["fight","fights","fought","fought"],
	find:["find","finds","found","found"],
	fit:["fit","fits","fitted","fitted"],
	flee:["flee","flees","fled","fled"],
	fling:["fling","flings","flung","flung"],
	fly:["fly","flies","flew","flown"],
	forbid:["forbid","forbids","forbade","forbidden"],
	forecast:["forecast","forecasts","forecast","forecast"],
	foresee:["foresee","foresees","foresaw","foreseen"],
	foretell:["foretell","foretells","foretold","foretold"],
	forget:["forget","forgets","forgot","forgotten"],
	forgive:["forgive","forgives","forgave","forgiven"],
	forsake:["forsake","forsakes","forsook","forsaken"],
	freeze:["freeze","freezes","froze","frozen"],
	frostbite:["frostbite","frostbites","frostbit","frostbitten"],
	fry:["fry","fries","fried","fried"],
	get:["get","gets","got","gotten"],
	give:["give","gives","gave","given"],
	go:["go","goes","went","gone"],
	grind:["grind","grinds","ground","ground"],
	grow:["grow","grows","grew","grown"],
	handwrite:["handwrite","handwrites","handwrote","handwritten"],
	hang:["hang","hangs","hung","hung"],
	have:["have","have","had","had"],
	hear:["hear","hears","heard","heard"],
	hew:["hew","hews","hewed","hewed"],
	hide:["hide","hides","hid","hidden"],
	hit:["hit","hit","hit","hit"],
	hold:["hold","holds","held","held"],
	hurt:["hurt","hurts","hurt","hurt"],
	inbreed:["inbreed","inbreeds","inbred","inbred"],
	inlay:["inlay","inlays","inlaid","inlaid"],
	input:["input","inputs","input","input"],
	keep:["keep","keeps","kept","kept"],
	kneel:["kneel","kneels","knelt","knelt"],
	know:["know","knows","knew","known"],
	lay:["lay","lays","laid","laid"],
	lead:["lead","leads","led","led"],
	leave:["leave","leaves","left","left"],
	lend:["lend","lends","lent","lent"],
	let:["let","lets","let","let"],
	lie:["lie","lies","lied","lied"],
	light:["light","lights","lit","lit"],
	lose:["lose","loses","lost","lost"],
	make:["make","makes","made","made"],
	mean:["mean","means","meant","meant"],
	meet:["meet","meets","met","met"],
	miscast:["miscast","miscasts","miscast","miscast"],
	misdeal:["misdeal","misdeals","misdealt","misdealt"],
	misdo:["misdo","misdoes","misdid","misdone"],
	mishear:["mishear","mishears","misheard","misheard"],
	mislay:["mislay","mislays","mislaid","mislaid"],
	mislead:["mislead","misleads","misled","misled"],
	misread:["misread","misreads","misread","misread"],
	misspend:["misspend","misspends","misspent","misspent"],
	mistake:["mistake","mistakes","mistook","mistaken"],
	misteach:["misteach","misteachs","mistaught","mistaught"],
	misunderstand:["misunderstand","misunderstands","misunderstood","misunderstood"],
	miswrite:["miswrite","miswrites","miswrote","miswritten"],
	offset:["offset","offsets","offset","offset"],
	outbid:["outbid","outbids","outbid","outbid"],
	outbreed:["outbreed","outbreeds","outbred","outbred"],
	outdo:["outdo","outdoes","outdid","outdone"],
	outdraw:["outdraw","outdraws","outdrew","outdrawn"],
	outdrink:["outdrink","outdrinks","outdrank","outdrunk"],
	outdrive:["outdrive","outdrives","outdrove","outdriven"],
	outfight:["outfight","outfights","outfought","outfought"],
	outfly:["outfly","outflies","outflew","outflown"],
	outgrow:["outgrow","outgrows","outgrew","outgrown"],
	outride:["outride","outrides","outrode","outridden"],
	outrun:["outrun","outruns","outran","outrun"],
	outsell:["outsell","outsells","outsold","outsold"],
	outshoot:["outshoot","outshoots","outshot","outshot"],
	outsit:["outsit","outsits","outsat","outsat"],
	outspeak:["outspeak","outspeaks","outspoke","outspoken"],
	outspeed:["outspeed","outspeeds","outsped","outsped"],
	outswear:["outswear","outswears","outswore","outsworn"],
	outthink:["outthink","outthinks","outthought","outthought"],
	outthrow:["outthrow","outthrows","outthrew","outthrown"],
	overbid:["overbid","overbids","overbid","overbid"],
	overbuild:["overbuild","overbuilds","overbuilt","overbuilt"],
	overbuy:["overbuy","overbuys","overbought","overbought"],
	overcome:["overcome","overcomes","overcame","overcome"],
	overdo:["overdo","overdoes","overdid","overdone"],
	overdraw:["overdraw","overdraws","overdrew","overdrawn"],
	overdrink:["overdrink","overdrinks","overdrank","overdrunk"],
	overfeed:["overfeed","overfeeds","overfed","overfed"],
	overhang:["overhang","overhangs","overhung","overhung"],
	overhear:["overhear","overhears","overheard","overheard"],
	overlay:["overlay","overlays","overlaid","overlaid"],
	overpay:["overpay","overpays","overpaid","overpaid"],
	override:["override","overrides","overrode","overridden"],
	overrun:["overrun","overruns","overran","overrun"],
	oversee:["oversee","oversees","oversaw","overseen"],
	oversell:["oversell","oversells","oversold","oversold"],
	overshoot:["overshoot","overshoots","overshot","overshot"],
	overtake:["overtake","overtakes","overtook","overtaken"],
	overthink:["overthink","overthinks","overthought","overthought"],
	overthrow:["overthrow","overthrows","overthrew","overthrown"],
	partake:["partake","partakes","partook","partaken"],
	pay:["pay","pays","paid","paid"],
	plead:["plead","pleads","pleaded","pleaded"],
	prebuild:["prebuild","prebuilds","prebuilt","prebuilt"],
	premake:["premake","premakes","premade","premade"],
	prepay:["prepay","prepays","prepaid","prepaid"],
	presell:["presell","presells","presold","presold"],
	preset:["preset","presets","preset","preset"],
	proofread:["proofread","proofreads","proofread","proofread"],
	prove:["prove","proves","proved","proven"],
	put:["put","puts","put","put"],
	quit:["quit","quits","quit","quit"],
	read:["read","reads","read","read"],
	reawake:["reawake","reawakes","reawoke","reawaken"],
	rebid:["rebid","rebids","rebid","rebid"],
	rebind:["rebind","rebinds","rebound","rebound"],
	rebuild:["rebuild","rebuilds","rebuilt","rebuilt"],
	recast:["recast","recasts","recast","recast"],
	recut:["recut","recuts","recut","recut"],
	redeal:["redeal","redeals","redealt","redealt"],
	redo:["redo","redoes","redid","redone"],
	redraw:["redraw","redraw","redrew","redrawn"],
	refit:["refit","refits","refitted","refitted"],
	regrind:["regrind","regrinds","reground","reground"],
	regrow:["regrow","regrows","regrew","regrown"],
	rehang:["rehang","rehangs","rehung","rehung"],
	rehear:["rehear","rehears","reheard","reheard"],
	relight:["relight","relights","relit","relit"],
	remake:["remake","remakes","remade","remade"],
	rend:["rend","rends","rent","rent"],
	repay:["repay","repays","repaid","repaid"],
	reread:["reread","rereads","reread","reread"],
	rerun:["rerun","reruns","reran","rerun"],
	resell:["resell","resells","resold","resold"],
	resend:["resend","resends","resent","resent"],
	reset:["reset","resets","reset","reset"],
	resew:["resew","resews","resewed","resewn"],
	retake:["retake","retakes","retook","retaken"],
	reteach:["reteach","reteaches","retaught","retaught"],
	retear:["retear","retears","retore","retorn"],
	retell:["retell","retells","retold","retold"],
	rethink:["rethink","rethinks","rethought","rethought"],
	retread:["retread","retreads","retread","retread"],
	retrofit:["retrofit","retrofits","retrofitted","retrofitted"],
	rewake:["rewake","rewakes","rewoke","rewaken"],
	rewear:["rewear","rewears","rewore","reworn"],
	reweave:["reweave","reweaves","rewove","rewoven"],
	rewin:["rewin","rewins","rewon","rewon"],
	rewind:["rewind","rewinds","rewound","rewound"],
	rewrite:["rewrite","rewrites","rewrote","rewritten"],
	rid:["rid","rids","rid","rid"],
	ride:["ride","rides","rode","ridden"],
	ring:["ring","rings","rang","rung"],
	rip:["rip","rips","ripped","ripped"],
	rise:["rise","rises","rose","risen"],
	run:["run","runs","ran","run"],
	saw:["saw","saws","sawed","sawed"],
	say:["say","says","said","said"],
	see:["see","sees","saw","seen"],
	seek:["seek","seeks","sought","sought"],
	sell:["sell","sells","sold","sold"],
	send:["send","sends","sent","sent"],
	set:["set","sets","set","set"],
	sew:["sew","sews","sewed","sewn"],
	shake:["shake","shakes","shook","shaken"],
	shed:["shed","sheds","shed","shed"],
	shit:["shit","shits","shit","shit"],
	shoot:["shoot","shoots","shot","shot"],
	show:["show","shows","showed","shown"],
	shrink:["shrink","shrinks","shrank","shrunk"],
	shut:["shut","shuts","shut","shut"],
	sing:["sing","sings","sang","sung"],
	sink:["sink","sinks","sunk","sunk"],
	sit:["sit","sits","sat","sat"],
	sleep:["sleep","sleeps","slept","slept"],
	slide:["slide","slides","slid","slid"],
	sling:["sling","slings","slung","slung"],
	slink:["slink","slinks","slinked","slinked"],
	slit:["slit","slits","slit","slit"],
	smell:["smell","smells","smelled","smelled"],
	sneak:["sneak","sneaks","sneaked","sneaked"],
	sow:["sow","sows","sowed","sowed"],
	speak:["speak","speaks","spoke","spoken"],
	speed:["speed","speeds","speeded","speeded"],
	spell:["spell","spells","spelled","spelled"],
	spend:["spend","spends","spent","spent"],
	spill:["spill","spills","spilled","spilled"],
	spin:["spin","spins","spun","spun"],
	spit:["spit","spits","spat","spat"],
	split:["split","splits","split","split"],
	spoil:["spoil","spoils","spoiled","spoiled"],
	spread:["spread","spreads","spread","spread"],
	spring:["spring","springs","sprang","sprung"],
	stand:["stand","stands","stood","stood"],
	steal:["steal","steals","stole","stolen"],
	stick:["stick","sticks","stuck","stuck"],
	sting:["sting","stings","stung","stung"],
	stink:["stink","stinks","stunk","stunk"],
	strike :["strike","strikes","struck","struck"],
	string:["string","strings","strung","strung"],
	strive:["strive","strives","strove","striven"],
	sublet:["sublet","sublets","sublet","sublet"],
	sunburn:["sunburn","sunburns","sunburned","sunburned"],
	swear:["swear","swears","swore","sworn"],
	sweat:["sweat","sweats","sweated","sweated"],
	sweep:["sweep","sweeps","swept","swept"],
	swell:["swell","swells","swelled","swelled"],
	swim:["swim","swims","swam","swum"],
	swing:["swing","swings","swung","swung"],
	take:["take","takes","took","taken"],
	teach:["teach","teaches","taught","taught"],
	tear:["tear","tear","tore","torn"],
	tell:["tell","tells","told","told"],
	think:["think","thinks","thought","thought"],
	"throw":["throw","throws","threw","thrown"],
	thrust:["thrust","thrusts","thrust","thrust"],
	tread:["tread","treads","trod","trodden"],
	"try":["try","tries","tried","tried"],
	unbend:["unbend","unbends","unbent","unbent"],
	unbind:["unbind","unbind","unbound","unbound"],
	unclothe:["unclothe","unclothes","unclothed","unclothed"],
	underbid:["underbid","underbids","underbid","underbid"],
	undercut:["undercut","undercuts","undercut","undercut"],
	underfeed:["underfeed","underfeeds","underfed","underfed"],
	undergo:["undergo","undergoes","underwent","undergone"],
	underlie:["underlie","underlies","underlay","underlain"],
	undersell:["undersell","undersells","undersold","undersold"],
	understand:["understand","understands","understood","understood"],
	undertake:["undertake","undertakes","undertook","undertaken"],
	underwrite:["underwrite","underwrites","underwrote","underwritten"],
	undo:["undo","undoes","undid","undone"],
	unfreeze:["unfreeze","unfreezes","unfroze","unfrozen"],
	unhang:["unhang","unhangs","unhung","unhung"],
	unhide:["unhide","unhides","unhid","unhidden"],
	unsling:["unsling","unslings","unslung","unslung"],
	unspin:["unspin","unspins","unspun","unspun"],
	unstick:["unstick","unsticks","unstuck","unstuck"],
	unstring:["unstring","unstrings","unstrung","unstrung"],
	unweave:["unweave","unweaves","unwove","unwoven"],
	unwind:["unwind","unwinds","unwound","unwound"],
	uphold:["uphold","upholds","upheld","upheld"],
	upset:["upset","upsets","upset","upset"],
	wake:["wake","wakes","woke","woken"],
	wear:["wear","wears","wore","worn"],
	weave:["weave","weaves","wove","woven"],
	weep:["weep","weeps","wept","wept"],
	wet:["wet","wets","wet","wet"],
	win:["win","wins","won","won"],
	wind:["wind","winds","wound","wound"],
	withdraw:["withdraw","withdraws","withdrew","withdrawn"],
	withhold:["withhold","withholds","withheld","withheld"],
	withstand:["withstand","withstands","withstood","withstood"],
	wring:["wring","wrings","wrung","wrung"],
	write:["write","writes","wrote","written"]
};
this.superlatives = {
	best:1,
	biggest:1,
	bulkiest:1,
	greatest:1,
	highest:1,
	largest:1,
	least:1,
	littlest:1,
	lowest:1,
	max:1,
	maximal:1,
	merest:1,
	minimal:1,
	most:1,
	mostest:1,
	outside:1,
	paramount:1,
	slightest:1,
	smallest:1,
	superlative:1,
	supreme:1,
	tiniest:1,
	top:1,
	topmost:1,
	ultimate:1,
	utmost:1,
	uttermost:1
};
}).call(this);
